name: Release BeDecorative plugin

on:
  push:
    tags:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18.x"

      - name: Build plugin
        run: |
          npm install
          npm run build

      - name: Create release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          tag="${GITHUB_REF#refs/tags/}"
          mkdir be-decorative
          cp main.js be-decorative
          cp manifest.json be-decorative
          cp styles.css be-decorative
          zip -r be-decorative.zip be-decorative/
          gh release create "$tag" \
            --title="$tag" \
            be-decorative.zip
